// get api for menu

export const GET_MENU_REQUEST = 'GET_MENU_REQUEST';
export const GET_MENU_SUCCESS = 'GET_MENU_SUCCESS';
export const GET_MENU_FAILURE = 'GET_MENU_FAILURE';

// ADD TO CART

export const ADD_TO_CART = 'ADD_TO_CART';


// ADD TO DELETE

export const DELETE_FROM_CART = 'DELETE_FROM_CART';


//  USER REGISTER 

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILURE  = 'USER_REGISTER_FAILURE '

// LOGIN
export const USER_LOGIN_REQUEST=" USER_LOGIN_REQUEST"
export const USER_LOGIN_SUCCESS=" USER_LOGIN_SUCCESS"
export const USER_LOGIN_FAILURE=" USER_LOGIN_FAILURE"

// PLACE TO ORDER

export const PLACE_ORDER_REQUEST='PLACE_ORDER_REQUEST'
export const PLACE_ORDER_SUCCESS='PLACE_ORDER_SUCCESS'
export const PLACE_ORDER_FAILURE='PLACE_ORDER_FAILURE'

